# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170418_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Not available', max_length=300)),
                ('text', models.TextField(default='Not available')),
            ],
        ),
    ]
