# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anger',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='calm',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='fear',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='happy',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(default='Not available', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='negative',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='neutral',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='positive',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='shame',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='sure',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='surprise',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
