# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170418_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Not available', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Not available', max_length=300, primary_key=True, serialize=False),
        ),
    ]
